### Login
POST /api/auth/login HTTP/1.1
Host: {{ host }}

{
    "email": "myemail@email.com",
    "password": "password"
}

### Register
POST /api/auth/register HTTP/1.1
Host: {{ host }}

{
    "name": "UserName",
    "email": "myemail@email.com",
    "password": "password"
}

### profile
GET /api/auth/profile HTTP/1.1
Host: {{ host }}
Authorization: {{token}}
