### Auth Login
POST /api/users/login HTTP/1.1
Host: {{ host }}

{
  "phone": "533475180",
  "password": "password",
  "auth_mode": "admin"
}

### Auth register
POST /api/users/register HTTP/1.1
Host: {{ host }}

{
  "name": "Admin Capote Quintana",
  "phone": "533475180",
  "password": "password",
  "password_confirmation": "password"
}

### Profile
GET /api/users/profile HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

### Ban
POST /api/users/ban/2 HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

### Message
POST /api/users/message HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

{
    "message": "Sample Message"
}

### Message
GET /api/users/profile HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

### Role request
POST /api/users/role-request HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

{
  "role": "shop_vendor",
  "subject": "Cuentapropia",
  "message": "Soy Juan"
}

### List Role Requests
GET /api/users/role HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

{
    "accepted": false
}

### Update Role Requests
PATCH /api/users/role/2 HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

{
  "accepted": true
}

### Update
POST /api/users/update HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

{
  "name": "Admin Update",
  "email": "newemail@email.com",
  "phone": "53375180",
  "address": "My new Address"
}
